"""Canonical domain contracts for Math Feedback AI."""

from .models import (
    CompletionGap,
    DiagnosisV1,
    ExampleProvenance,
    HintPlan,
    Issue,
    LeakageCheckResult,
    LeakageViolation,
    Problem,
    ReferenceSolution,
    SolutionStep,
    StepAssessment,
    StepParseResult,
    StudentAttempt,
    TutorDecision,
    TutoringExampleV1,
    TutorResponse,
    TutorResult,
)
from .taxonomy import (
    ISSUE_TAXONOMY_VERSION,
    IssueCode,
    LeakageSeverity,
    OverallStatus,
    ReferenceRelation,
    RevealLevel,
    StepParseStrategy,
    StepStatus,
    TutorAction,
    TutorMode,
)

__all__ = [
    "ISSUE_TAXONOMY_VERSION",
    "CompletionGap",
    "DiagnosisV1",
    "ExampleProvenance",
    "HintPlan",
    "Issue",
    "IssueCode",
    "LeakageCheckResult",
    "LeakageSeverity",
    "LeakageViolation",
    "OverallStatus",
    "Problem",
    "ReferenceRelation",
    "ReferenceSolution",
    "RevealLevel",
    "SolutionStep",
    "StepAssessment",
    "StepParseResult",
    "StepParseStrategy",
    "StepStatus",
    "StudentAttempt",
    "TutoringExampleV1",
    "TutorAction",
    "TutorDecision",
    "TutorMode",
    "TutorResponse",
    "TutorResult",
]
